// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;

#nullable disable

namespace UseChangeProxies
{
    public partial class Customers : INotifyPropertyChanging, INotifyPropertyChanged
    {
        private int id;
        private string name;
        private string address;
        private int creditLevel;

        public virtual int Id 
        { 
            get => id;
            set
            {
                id = value;
                OnPropertyChanged(nameof(Id));
            }
        }
        public virtual string Name 
        {
            get => name;
            set
            {
                name = value;
                OnPropertyChanged(nameof(Name));
            }
        }

        public virtual string Address 
        { 
            get => address;
            set
            {
                address = value;
                OnPropertyChanged(nameof(Address));
            }
        }

        public virtual int CreditLevel
        {
            get => creditLevel;
            set
            {
                creditLevel = value;
                OnPropertyChanged(nameof(CreditLevel));
            }
        }

        private void OnPropertyChanging(string propName)
        {
            PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propName));
        }

        private void OnPropertyChanged(string propName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propName));
        }

        public event PropertyChangingEventHandler PropertyChanging;
        public event PropertyChangedEventHandler PropertyChanged;
    }
}