// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace UseComputeSql
{
    public partial class Orders
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public decimal? Price { get; set; }
        public decimal? Qty { get; set; }
        public decimal? Total { get; set; }
    }
}