// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace RelationsIncludeFilter
{
    public partial class Orders
    {
        public Orders()
        {
            OrderDetails = new HashSet<OrderDetails>();
        }

        public int Id { get; set; }
        public DateTime OrderDate { get; set; }
        public string CustomerName { get; set; }

        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
    }
}